title: Harry McClouds Data Science Portfolio
description: Harry is a Data Science Apprentice studying with BPP university. Within this portfolio are examples of some of the projects he has completed thus far.
theme: jekyll-theme-slate
show_downloads: true
